### ISSUE TITLE
Broken menu

### ISSUE THREAD

**Issue by GreenWeegeeCantCode** [maxnut/GDmenu#109]
Ok so i just extracted all files in my GD folder, however i just get this error:

![image](https://github.com/maxnut/GDMegaOverlay/assets/145769578/a37e3912-a06d-4825-81b9-30667eef951c)

After this, the xinput dll file gets deleted automatically, without it GD launches perfectly fine but i cant open the menu.

**Comment by GreenWeegeeCantCode** [comment]
If i put the xinput back i get the error again so i guess its a problem with that

**Comment by GreenWeegeeCantCode** [comment]
i just installed the new version and i still get this error

**Comment by maxnut** [comment]
if xinput gets deleted its your antivirus, disable it or make an exception

**Comment by GreenWeegeeCantCode** [comment]
I get no threat notification when trying to launch gd with mega overlay and xinput just gets deleted like it never existed
