### ISSUE TITLE
gd not opening after gd mega overlay

### ISSUE THREAD

**Issue by ilyaBurec** [maxnut/GDmenu#113]
so i tried out gd mega overlay its quite cool alternative but when i closed the game and opened again gd just doesnt open when gd overlay files are here i even cleaned up temp tried to find save data of gd mega overlay in appdata and even reinstalling the game B-BUT NOTHING WORKS! plz maxnut release a hotfix to this problem!

Uploading 2024-01-03 23-54-42.mp4...

**Comment by WibleWobble** [comment]
Had the same issue. For some reason uninstalling through steam doesnt work, but manually deleting the entire GD folder from your steamlibrary directory then reinstalling worked. You will have to put in the overlay again.

**Comment by maxnut** [comment]
i need details

**Comment by Sapphire-code** [comment]
> so i tried out gd mega overlay its quite cool alternative but when i closed the game and opened again gd just doesnt open when gd overlay files are here i even cleaned up temp tried to find save data of gd mega overlay in appdata and even reinstalling the game B-BUT NOTHING WORKS! plz maxnut release a hotfix to this problem!
> 
> Uploading 2024-01-03 23-54-42.mp4...

Have you tried seeing the version that you were installing? Mismatch between game versions and the hack versions can result in GD not opening, check if the one you installed is for your game version. If you're on 2.2, then install the 2.2 version, if you're still on 2.1 for some reason then it might be time to either update, or just use the 2.1 version from the 2.1 branch for the repository.

**Comment by asrindenizeye** [comment]
Hello Today I create

 my account
