### ISSUE TITLE
unordered_map instead of unordered_set?

### ISSUE THREAD

**Issue by Stronkkey** [maxnut/GDmenu#117]
Macrobot.cpp contains a variable called 'checkpoints' with type `std::unordered_map<void*, Macrobot::CheckpointData>`. Wouldn't it make more sense to use an unordered set instead of unordered map?

**Comment by maxnut** [comment]
what? no, its a map because it maps checkpoint pointers to checkpoint data

**Comment by Stronkkey** [comment]
Nvm misread it.
Edit: It's not immediately appearant what type `void*` is pointing to. So I think it would be logical should to add  a comment explaining that points to a checkpoint pointer.

**Comment by Stronkkey** [comment]
@maxnut is there are a reason why frame data is stored as `double` instead of something like `uint64_t`? Because once you get past like 36028797018963968, the rounding error is higher than 1.
