### ISSUE TITLE
New 2.05 version marked as malicious by windows defender.

### ISSUE THREAD

**Issue by Sapphire-code** [maxnut/GDmenu#119]
Here's the type it provides: Trojan:Script/Wacatac.B!ml

Hope this issue is solved as soon as possible!

**Comment by Stronkkey** [comment]
This can't really be solved without microsoft doing anything and I doubt they care.

**Comment by maxnut** [comment]
^^
just add it as an exception

**Comment by Sapphire-code** [comment]
> ^^ just add it as an exception

I see, thanks! I usually have trust issues regarding these things, so I guess ill make sure it's safe before installing this time.

**Comment by maxnut** [comment]
if you really don't trust it just build the source yourself

**Comment by RevolvingMadness** [comment]
How do I build from source? I want to do this so I can get 2.204

**Comment by racyt** [comment]
guys it doesnt work for 2.204

**Comment by Sapphire-code** [comment]
> guys it doesnt work for 2.204

The latest supported version is 2.202

**Comment by LofyyJAM** [comment]
My Windows Defender says the 2.201 gdmo is a virus, wacatac b!ml, so its probably just a false positive
