### ISSUE TITLE
Inconsistent indentation style

### ISSUE THREAD

**Issue by Stronkkey** [maxnut/GDmenu#120]
![2024-01-04T15:14:03,160642010+01:00](https://github.com/maxnut/GDMegaOverlay/assets/92468390/7e129bb4-5a49-40ce-8f7c-04266a987f57)
Tab indentation
![2024-01-04T15:13:50,733258540+01:00](https://github.com/maxnut/GDMegaOverlay/assets/92468390/8b0aedf5-f6d8-4801-bfb1-67a15d3f2796)
4 Space indentation
![2024-01-04T15:15:14,518659966+01:00](https://github.com/maxnut/GDMegaOverlay/assets/92468390/2fc97b9e-5212-4282-8298-77f1433defc5)
This is going to look funny with 8 tab indentation.
So, which indentation style is correct?

**Comment by maxnut** [comment]
use tab indentation. i believe space indentation was used by @SpaghettDev because thats who worked on that file, i may be wrong tho

**Comment by Stronkkey** [comment]
Are you gonna fix it or no?

**Comment by SpaghettDev** [comment]
> Are you gonna fix it or no?

fixed in [f0ae9e4](https://github.com/maxnut/GDMegaOverlay/commit/f0ae9e4630c200b1f3521a7b56a164a5d11cc46c)
