### ISSUE TITLE
gdmo macro bot freezes game when record button is pressed

### ISSUE THREAD

**Issue by bsaweee** [maxnut/GDmenu#122]

**Comment by maxnut** [comment]
send settings

**Comment by bsaweee** [comment]
![Screenshot 2024-01-04 213542](https://github.com/maxnut/GDMegaOverlay/assets/155666932/c10369d7-b1f1-455a-93c4-1e4a5d693850)
![Screenshot 2024-01-04 213558](https://github.com/maxnut/GDMegaOverlay/assets/155666932/e77afc1c-3aa5-44ba-b708-8956eb064cd9)
![Screenshot 2024-01-04 213621](https://github.com/maxnut/GDMegaOverlay/assets/155666932/fd1da26f-1e7a-4719-8e2e-f825e33ce3f5)
![Screenshot 2024-01-04 213652](https://github.com/maxnut/GDMegaOverlay/assets/155666932/22f7f71f-4c3a-4c18-9707-b4598429ac3d)
![Screenshot 2024-01-04 213719](https://github.com/maxnut/GDMegaOverlay/assets/155666932/36c7a228-5b2b-4a95-bec3-2c97ccd7dc66)
![Screenshot 2024-01-04 213734](https://github.com/maxnut/GDMegaOverlay/assets/155666932/b5ec8283-4e1f-4927-8c19-5e33922e9aec)
![Screenshot 2024-01-04 214152](https://github.com/maxnut/GDMegaOverlay/assets/155666932/d80111c9-7e8f-48ce-8e92-54ba4a989a55) heres my settings is there anything i need to turn off or on for it to not crash my game?

**Comment by bsaweee** [comment]
nvm fixed it just had to change my fps to 120
