### ISSUE TITLE
I can't download the file

### ISSUE THREAD

**Issue by Mar1Xd** [maxnut/GDmenu#123]
Whenever I try to download the file, it says that it's a virus. Even if I click "download anyway" it won't let me. Yesterday I downloaded it successfully and it was working in game. But when I woke up today, it didn't work, so I deleted it. Today I tried multiple times to redownload the files and still nothing. Can somebody help me with this problem?

**Comment by maxnut** [comment]
idk disable virus detection. not a code issue anyway

**Comment by Mar1Xd** [comment]
> idk disable virus detection. not a code issue anyway

Yes,I get that.But It was already working 2 days ago(in game),but when I tried yesterday it didn't work(it was just normal gd without the overlay).That's why I even deleted it.

**Comment by SpaghettDev** [comment]
> > idk disable virus detection. not a code issue anyway
> 
> Yes,I get that.But It was already working 2 days ago(in game),but when I tried yesterday it didn't work(it was just normal gd without the overlay).That's why I even deleted it.

be sure to copy over "xinput9_1_0.dll"

**Comment by MysticAx0lotl** [comment]
Duplicate of https://github.com/maxnut/GDMegaOverlay/issues/119.
