### ISSUE TITLE
Linux error

### ISSUE THREAD

**Issue by josefv2** [maxnut/GDmenu#124]
First of all, thanks for doing this menu for free! It had incredible quality and on par with Mega Hack.

Unfortunately I can't use it on 2.2. The game runs fine, but when I install GDMO this error pops:

`0230:err:sync:RtlpWaitForCriticalSection section 7BC6D440 "../dlls/ntdll/loader.c: loader_section" wait timed out in thread 0230, blocked by 023c, retrying (60 sec)`

In 2.1 it worked fine, I downgraded to 2.1 and installed the old version and that one works. GD 2.2 without the menu also runs fine. 

Tested on multiple Protons with Steam and on Wine. Used versions 2.0 and 2.10 of GDMO. I also updated 1.41 and tried coping the files.

**Comment by lexira1n** [comment]
interesting as i can get it to run on linux

**Comment by maxnut** [comment]
join the discord, there's people that are able to give linux support there
