### ISSUE TITLE
Sir is this a virus 💀💀

### ISSUE THREAD

**Issue by Andydev503** [maxnut/GDmenu#125]
![image](https://github.com/maxnut/GDMegaOverlay/assets/81941065/3a54b7d5-9f3a-43c0-8d11-7a71589f445b)
this is very concerning

**Comment by TwentySixOfficial** [comment]
most likely not, it does the same with megahack v8.

**Comment by maxnut** [comment]
no

**Comment by MysticAx0lotl** [comment]
Duplicate of https://github.com/maxnut/GDMegaOverlay/issues/119.
