### ISSUE TITLE
macro freezes player

### ISSUE THREAD

**Issue by jimmyjamescool** [maxnut/GDmenu#133]
![shitwontwork](https://github.com/maxnut/GDMegaOverlay/assets/131569352/a553bedc-c17c-4237-95ac-fbc5809b8860)
audio and everything else works fine, it just wont move

even with corrections

**Comment by Stronkkey** [comment]
Can confirm this happens with the newest version.

**Comment by ImaDoor2785** [comment]
yup happens to me too

**Comment by ImaDoor2785** [comment]
changing your fps to your refresh rate and having vsync on fixed it for me

**Comment by jimmyjamescool** [comment]
> changing your fps to your refresh rate and having vsync on fixed it for me

didnt work and im on latest ver

**Comment by ImaDoor2785** [comment]
well its an fps issue i think and you need to restart your game after changing it 
try 60 or 120 or whatever your refresh rate is you might get lucky thats what worked for me

its been an issue before
https://github.com/maxnut/GDMegaOverlay/issues/122

**Comment by ImaDoor2785** [comment]
found out its not an fps issue its just that the fps option isnt toggled on
so just set your fps and the remember to turn it on

**Comment by Stronkkey** [comment]
I think this happens maybe because force smooth fix isn't turned on? Should be fixed regardless.

**Comment by maxnut** [comment]
should be fixed on new ver
