### ISSUE TITLE
Mod Suggestion

### ISSUE THREAD

**Issue by ghost** [maxnut/GDmenu#134]
I've made a list with some mod ideas and put them in categories. If you have questions about any mod I put in my list, feel free to ask me in comments.
![IMG_20240106_123825](https://github.com/maxnut/GDMegaOverlay/assets/155563361/29b0ab30-9f9e-4214-a490-669ed6ceb2fb)

**Comment by ghost** [comment]
In the last mod, you have to select the shard type.

**Comment by maxnut** [comment]
this is not a section for suggestions. for that join the discord
