### ISSUE TITLE
I cant download it

### ISSUE THREAD

**Issue by aqcu** [maxnut/GDmenu#135]
When i tried to download the file for gdmo it said it had a trojan and i know that it doesnt have a virus but it instantly deletes the files which has the "virus" in it and btw opera gx says its a "virus" and i cant download it.
![image_2024-01-06_131759129](https://github.com/maxnut/GDMegaOverlay/assets/155756191/3cfeb4d5-35d1-4721-ae34-f545b6d52be6)

**Comment by maxnut** [comment]
omfg disable virus detection stop reporting this as a fucking code issue

**Comment by MysticAx0lotl** [comment]
Duplicate of https://github.com/maxnut/GDMegaOverlay/issues/119
