### ISSUE TITLE
Practice Music Sync Feature(add this)

### ISSUE THREAD

**Issue by Frouk3** [maxnut/GDmenu#137]
`PlayLayer + 0x2A75 - Practice Music Sync`
Auto Assembler Script:
```asm
[ENABLE]
GeometryDash.exe+2E0EBA: // try to sync in?
db 90 90
GeometryDash.exe+002E430E: // on death stop
db EB
GeometryDash.exe+2DD346: // ?? (in PlayLayer update func(maybe))
db 90 90
GeometryDash.exe+2DD377: // ^^^
db 90 90
GeometryDash.exe+2E2927: // on death set sync if(checkpointNum > 0)
db EB
GeometryDash.exe+002E4F35: // actual sync?
db EB
GeometryDash.exe+002E54B8: // on retry no checkpoints
db 90 90 90 90 90 90
GeometryDash.exe+002E517A: // jne -> jmp, was accessed
db EB
[DISABLE]
GeometryDash.exe+2E0EBA: // try to sync in?
db 74 0C
GeometryDash.exe+002E430E: // on death stop
db 75
GeometryDash.exe+2DD346: // ?? (in PlayLayer update func(maybe))
db 74 09
GeometryDash.exe+2DD377: // ^^^
db 74 03
GeometryDash.exe+2E2927: // on death set sync if(checkpointNum > 0)
db 75
GeometryDash.exe+002E4F35: // actual sync?
db 75
GeometryDash.exe+002E54B8: // on retry no checkpoints
db 0F 84 97 00 00 00
GeometryDash.exe+002E517A: // jne -> jmp, was accessed
db 75
```

**Comment by Frouk3** [comment]
Practice Music Sync: `PlayLayer + 0x27AD`
GameManager variable: "0125"
Updated one(2.201):
```asm
[ENABLE]
GeometryDash.exe+2E3B59:
db EB 0F
[DISABLE]
GeometryDash.exe+2E3B59:
db 74 18
```
P.S. there's patch for condition jne/je or patch `mov byte ptr [eax+27AD]`, written later, its your choice to choose whatever it should patch

**Comment by jimmyjamescool** [comment]
You could’ve just made a pr but cool

**Comment by Frouk3** [comment]
its stuff in json, the mega overlay renders tabs via json

**Comment by pastadudes** [comment]
unlock all also unlocks practice music sync

**Comment by Stronkkey** [comment]
> its stuff in json, the mega overlay renders tabs via json

Why is that even the case? It just makes it harder to update the addresses because they have to use a new release for that.

**Comment by maxnut** [comment]
> > its stuff in json, the mega overlay renders tabs via json
> 
> Why is that even the case? It just makes it harder to update the addresses because they have to use a new release for that.

no need to recompile, also with geode you have to update anyways so it's not a problem anymore

**Comment by maxnut** [comment]
can you explain what this does exactly? also is this updated for 2.204

**Comment by Frouk3** [comment]
> can you explain what this does exactly? also is this updated for 2.204

1. Practice music hack for lazy players that don't want to collect 2000 diamonds, enabled without going to settings(in pause) for "Practice Music Sync" and toggle it
2. No, actual version is here 
```asm
GeometryDash.exe+002E5A79:
db toggle // 1 for enable, 0 for disable
```

**Comment by Stronkkey** [comment]
@maxnut I am guessing the cheat code would look like this
```        {
            "description": "Enables Practice Music Sync without having to buy it from the shop.",
            "name": "Practice Music Sync",
            "opcodes": [
                {
                    "address": "0x002e5a79",
                    "off": "00 00 00 00 00 00",
                    "on": "00 00 00 00 00 01"
                }
            ],
            "toggle": false
        }
```
#CMIIAW

**Comment by maxnut** [comment]
added in 41f0794eff9d55fe17869d82464fe67e0f07d538
