### ISSUE TITLE
VirusTotal found viruses

### ISSUE THREAD

**Issue by l0l1boy** [maxnut/GDmenu#149]
**VirusTotal** writes about 19 viruses: Trojan, some Gen:Variant.Fragtor.417121 and RDN/Generic.dx; Ransom.Win32.Wacatac.ns, etc.
Even if it doesn’t say that it’s malicious, I’d rather not download it

**Comment by iAndyHD3** [comment]
false positives are normal for mod menus. the source is literally there for you to see. if you do not trust the prebuilt binary, feel free to build it yourself

**Comment by Stronkkey** [comment]
Duplicate of #119.
