### ISSUE TITLE
So uhh i have 3 new ideas for GDMO

### ISSUE THREAD

**Issue by Coooooooooooooooooooooooooolx** [maxnut/GDmenu#150]
1: Shop Bypass
this will unlock all shops and allow you to get all items in all shops for free
2: Chest Bypass
This will allow you to open any chest for free
3:Add diamonds/orbs
this will allow you to add orbs and diamonds from thin air for example
there will be 2 boxes 1 for orbs 1 for diamonds
if you tybe 5000 into the orb box you get 5000 orbs in your account and if you type 10000 into the diamond box it will add 10000 diamonds to your account
please share your thoughts in the comments maxnut

**Comment by maxnut** [comment]
don't request here do it in the discord server
