### ISSUE TITLE
Game crashes after using startpos switcher

### ISSUE THREAD

**Issue by OneCopperPipe** [maxnut/GDmenu#156]
after the 2.201 fix for GDoverlay, the startpos switcher works until you try to switch to the first or basic spawn, at the start of the level. you can switch to it from last startpos, but trying to go all the way back from the first startpos to basic spawn causes it to crash, and then leaving the basic spawn causes game to crash aswell. no idea why, it just does, and i tried being as informative as possible.

**Comment by hexaveiii** [comment]
most likely just a first-time issue on your end, this happens to me sometimes too but it really only crashes one time and then said feature works every time afterwards.
