### ISSUE TITLE
GD crashes

### ISSUE THREAD

**Issue by GamingIQYT** [maxnut/GDmenu#157]
When I first added the mod. It didn't crash. until I closed GD, then when I reopened it wouldn't work, it would launch. but I removed the files and it opens. Then I close it and add the files back. It's an infinite loop

**Comment by RSHOwner** [comment]
I can tell you under the age of 12 just by reading this.

**Comment by maxnut** [comment]
antivirus probably

**Comment by GamingIQYT** [comment]
@RSHOwner If you wont help me then fuck off

**Comment by MysticAx0lotl** [comment]
> @RSHOwner If you wont help me then fuck off

You're the one misusing the Issues tab my guy
