### ISSUE TITLE
Copy hack bug

### ISSUE THREAD

**Issue by TV46** [maxnut/GDmenu#158]
When you enable copy hack along with the copy button the remove from server button also appears on the level even though it does nothing please fix this

**Comment by RSHOwner** [comment]
i donno, ask rubrub to stop adding anti cheat shit

**Comment by Kingminer7** [comment]
> When you enable copy hack along with the copy button the remove from server button also appears on the level even though it does nothing please fix this

i think it does this because it makes geometry dash think you created the level, so it shows the copy and delete from server buttons

**Comment by maxnut** [comment]
it doesn't really matter
