### ISSUE TITLE
Crash, Pitch shifter, Macro and Startpos switcher

### ISSUE THREAD

**Issue by Switchingdo** [maxnut/GDmenu#160]
Hi, i have some problems with gdmenu:
1-The game crash sometime randomly, but the most of the time, the game crash because of the startpos switcher.
2-The pitch shifter is completly broken. Every time i open and close the cheat tab, the pitch go more and more lower.
3-I attempted to make a showcase, and the macro, completly randomly, slowed down the game for 5 seconds, before getting back normaly. I reattempted, with the macro, the same level, and the bug disapere, wich is very strange.
4-The startpos switcher is very very buggy. Firstly, i have to go left, to go right and to go right, to go left, wich is not normal at all. Also, if i didnt play the startpos in the editor, and i switch to this startpos, my game crash. And when i switch startpos quickly, my game crash !

**Comment by Stronkkey** [comment]
The issues don't accept bug reports, use the [discord server](https://discord.gg/nbDjEg7SSU) to report bugs instead.
