### ISSUE TITLE
No indication of update

### ISSUE THREAD

**Issue by TV46** [maxnut/GDmenu#163]
My idea is to add a menu to check the mod versions and to update it and also add a pop up if it auto updates

**Comment by Stronkkey** [comment]
It used to do that but it doesn't anymore??? The funniest part was that it was added in the LAST ever release of the 2.1 branch.

**Comment by SpaghettDev** [comment]
GDMO 2.2 has been re-built from the ground up, so all previous 2.113 features need to be re-implemented.
This feature is planned, but with the constant updates it'll take some time.

**Comment by TV46** [comment]
Thanks

**Comment by SpaghettDev** [comment]
Added in commit b20a44c
