### ISSUE TITLE
a message for maxnut 

### ISSUE THREAD

**Issue by Coooooooooooooooooooooooooolx** [maxnut/GDmenu#165]
ya know you always say to use discord for requests BUT you need to know that not everybody can use discord like me so you sould accept requests here and discord

**Comment by Coooooooooooooooooooooooooolx** [comment]
also what is your reason for only accepting requests on discord ?

**Comment by maxnut** [comment]
no

**Comment by maxnut** [comment]
ur probably 5

**Comment by MysticAx0lotl** [comment]
> also what is your reason for only accepting requests on discord ?

Github issues are for problems with the code. They're **issues**. Keeping requests on Discord helps keep this repo (somewhat) organized. Discord is also far easier to moderate
