### ISSUE TITLE
@maxnut

### ISSUE THREAD

**Issue by hexaveiii** [maxnut/GDmenu#166]
Just a question. is there a discord server for this such as for updates and more? just wondering so i can join and get up-to-date with the new menu features and downloads.

**Comment by Coooooooooooooooooooooooooolx** [comment]
uhhh yeah ?

**Comment by Coooooooooooooooooooooooooolx** [comment]
here is the link : https://discord.com/invite/nbDjEg7SSU

**Comment by maxnut** [comment]
bruh

**Comment by Stronkkey** [comment]
Bruh when opening an issue you will see 2 LINKS to the discord server

**Comment by hexaveiii** [comment]
> Bruh when opening an issue you will see 2 LINKS to the discord server

I didn't see them, they didn't pop up for me lmfao
