### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by STPv22** [maxnut/GDmenu#175]
It would me nice if there was a description of the lesser-known hax, like macro bot, and also "press tab to open hacks," in the readme file.

**Comment by maxnut** [comment]
don't post requests here please

**Comment by STPv22** [comment]
> don't post requests here please

I do not have discord, but ok.

**Comment by MysticAx0lotl** [comment]
> I do not have discord, but ok.

Create an account (or look two tabs to your left, where you _can_ submit suggestions)

**Comment by STPv22** [comment]
> > I do not have discord, but ok.
> 
> Create an account (or look two tabs to your left, where you _can_ submit suggestions)

Oh crap sorry
