### ISSUE TITLE
THIS IS A TROJAN VIRUS

### ISSUE THREAD

**Issue by DXBOSS12** [maxnut/GDmenu#177]
I'm Not Sure if this is right but after trying to download the latest version of the GDMO my Windows Security stopped the download. I went on VirusTotal to scan it and it is flagged as a **Trojan Virus**. This never happend before just in the latest version (compatible with 2.204).
![Screenshot 2024-01-17 201235](https://github.com/maxnut/GDMegaOverlay/assets/156956886/3e00c985-52b3-4125-8387-533d556f6fcf)

**Comment by CattoDev** [comment]
you go girlboss!

**Comment by Fleeym** [comment]
you better delete it quick! who knows how many other trojans this very dangerous trojan installed on your machine...

**Comment by maxnut** [comment]
just check closed issues i dont even wanna comment this properly

**Comment by MysticAx0lotl** [comment]
💀

**Comment by Stronkkey** [comment]
Duplicate of #119.
