### ISSUE TITLE
GDMO Wont Open When Pressing Tab

### ISSUE THREAD

**Issue by kkmfd-Offical** [maxnut/GDmenu#180]
**Note: It's preferred if you post your code review in the Merge request (if there is one) instead of here if possible.**

I Extracted the Files and verified the integrity but it wont show the Credits when launching the game and that means the mod menu wont load

**Comment by Vencixa** [comment]
menu is not updated for 2.204 my guy

**Comment by maxnut** [comment]
bro literally selected code review and proceeded to post a menu bug anyways
