### ISSUE TITLE
Trojan/Malware detected.

### ISSUE THREAD

**Issue by AdhaXy** [maxnut/GDmenu#190]
I ran the zip files nad individual files through VirusTotal, Bitfender, Norton and McAfee. They all found it malicious and deteced MULTIPLE trojans and malwares. I've downloaded this files long time ago and when i scan that files its safe, this update version however... Yh

**Comment by SpaghettDev** [comment]
Maybe open your eyes a bit and read the pinned issue before opening an issue?
Here, if you can't be bothered to use your brain a bit: #181

**Comment by Stronkkey** [comment]
Duplicate of #119.
