### ISSUE TITLE
...

### ISSUE THREAD

**Issue by STPv22** [maxnut/GDmenu#196]
Waiting for 2.204...

**Comment by maxnut** [comment]
holy shit actual braindead behavior

**Comment by MysticAx0lotl** [comment]
It's times like these I wish I could remember how to ban people from repos

**Comment by STPv22** [comment]
> It's times like these I wish I could remember how to ban people from repos

Who are you trying to ban? Me or the owner of the repo?

**Comment by MysticAx0lotl** [comment]
> > It's times like these I wish I could remember how to ban people from repos
> 
> Who are you trying to ban? Me or the owner of the repo?

You

**Comment by STPv22** [comment]
> > > It's times like these I wish I could remember how to ban people from repos
> > 
> > 
> > Who are you trying to ban? Me or the owner of the repo?
> 
> You

Bruh ok... You could just Google it.
