### ISSUE TITLE
Microsoft defender seeing trojan

### ISSUE THREAD

**Issue by Yaziy** [maxnut/GDmenu#200]
idk Microsoft defender seeing trojan

**Comment by MysticAx0lotl** [comment]
#181

**Comment by Stronkkey** [comment]
@MysticAx0lotl bruh it's a duplicate of #119

**Comment by MysticAx0lotl** [comment]
> @MysticAx0lotl bruh it's a duplicate of #119 

I know, the issue I referenced is my faq/readme issue, which addresses this
