### ISSUE TITLE
avoid this to not break unicode paths

### ISSUE THREAD

**Issue by matcool** [maxnut/GDmenu#201]
https://github.com/maxnut/GDMegaOverlay/blob/edb62ab109af6ac79a7d75d86b6601168461828f/src/main.cpp#L28-L33

use the path's operator/ instead, code would be cleaner too
`Mod::getSavePath() / "macros"`

Calling .string() on a path **will** break on non ascii paths, because windows. Avoid converting a path to string if possible, as the path itself can handle unicode characters. if you need it as a string, use wstring and convert to utf-8 if needed

**Comment by maxnut** [comment]
should be fixed
