### ISSUE TITLE
I cant close the menu

### ISSUE THREAD

**Issue by CosmoReator** [maxnut/GDmenu#202]
https://github.com/maxnut/GDMegaOverlay/assets/156057628/16c1a7e6-727b-4abb-af01-aefa06403746

how

**Comment by relaxingOcean** [comment]
just dont use two mod hacks, easy
or customize the two mod hacks to have different keybinds to open/close

**Comment by maxnut** [comment]
dont use two menus bruh

**Comment by Rustring** [comment]
Rebind openhack to shift or anything other than tab, that works for me lol.
