### ISSUE TITLE
Playing from a startpos in editor crashes Geometry Dash

### ISSUE THREAD

**Issue by relaxingOcean** [maxnut/GDmenu#207]
While editing my level, I wanted to test it from a point (I was going to update it to move things around) and voila, a long-listed error message popped up. Here's what it says: (yes I use Geode)

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll
Faulty Mod: maxnu.gd_mega_overlay
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 63025CA9 (maxnu.gd_mega_overlay.dll + 35ca9)
Number Parameters: 2

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 35ca9
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 33f80
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 3676c
 - 138F022B
 - 138F1076
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + b229
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 3ba6
 - 138F0E97
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 71d61
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 6a556
 - 138F0E97
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 107031 (cocos2d::CCTimer::update + 97)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 106ec4 (cocos2d::CCScheduler::update + 276)
 - 00822536
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 5a86
 - 00822357
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\gdutilsdevs.gdutils\gdutilsdevs.gdutils.dll + 22536
 - 00822357
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\gdutilsdevs.gdutils\gdutilsdevs.gdutils.dll + 22556
 - 00822357
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 3bad6
 - 00822357
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 32026
 - 00822357
 - 00822357
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + c5976 (gdMainHook + 406 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:58)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

Could you tell me what happened and how to prevent this from happening again?

**Comment by maxnut** [comment]
will look into it

**Comment by relaxingOcean** [comment]
thanks

**Comment by maxnut** [comment]
should be fixed
