### ISSUE TITLE
After enabling Icon Hack, Menu won't open.

### ISSUE THREAD

**Issue by TabFox-log** [maxnut/GDmenu#209]
After the icon hack was enabled, I tried playing a level and the menu didn’t open when I tried to open it.

**Comment by SpaghettDev** [comment]
Are you sure enabling Icon Hack was the cause? Because this doesn't make sense...

**Comment by Rustring** [comment]
Icon hack works perfectly for me

**Comment by TabFox-log** [comment]
I'll check again later when I can

**Comment by TabFox-log** [comment]
I'll also link the mods that I’m using as well

**Comment by TabFox-log** [comment]
![image](https://github.com/maxnut/GDMegaOverlay/assets/139163045/03a8c9c1-defb-4f6a-b19e-2f69f500c9fa)
so those are the mods

**Comment by Stronkkey** [comment]
Are you sure its just icon hack? You can edit the mod file to disable icon hack incase that fixes it.

**Comment by TabFox-log** [comment]
> Are you sure its just icon hack? You can edit the mod file to disable icon hack incase that fixes it.

i'll try thanks

**Comment by TabFox-log** [comment]
btw how do i do that?

**Comment by SpaghettDev** [comment]
It's better to just re-install the menu from the index. Just be sure to check "Delete mod save data" when uninstalling it.

**Comment by TabFox-log** [comment]
> It's better to just re-install the menu from the index. Just be sure to check "Delete mod save data" when uninstalling it.

Alright, I'm going to try it.

**Comment by TabFox-log** [comment]
Issue solved, thanks
