### ISSUE TITLE
Geometry Dash Crashes

### ISSUE THREAD

**Issue by LouisYouTube** [maxnut/GDmenu#211]
Sometimes after I record a macro and then play a different level the game crashes

**Comment by LouisYouTube** [comment]
This is the message it sent me when gd crashes:

2024-01-31T21:01:39+0700
Whoopsies! An unhandled exception has occured.
It appears that the crash occurred while executing code from the "maxnu.gd_mega_overlay" mod. Please submit this crash report to its developer (maxnu & SpaghettDev) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.12
Loader Commit: 9cb3cf1
Bindings Commit: a684cc0
Installed mods: 24
Problems: 0

== Exception Information ==
Faulty Module: E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll
Faulty Mod: maxnu.gd_mega_overlay
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 6E3BD36D (maxnu.gd_mega_overlay.dll + 5d36d)
Number Parameters: 2

== Stack Trace ==
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 5d36d
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 6334c
 - 18641AEB
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 192329
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 2dc92d
 - 01343A26
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\techstudent10.discord_rich_presence\techstudent10.discord_rich_presence.dll + 145b9
 - 0134384F
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\izzy.practice_sync\izzy.practice_sync.dll + 3976
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\izzy.practice_sync\izzy.practice_sync.dll + 1a34
 - 0134384F
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\cvolton.betterinfo\cvolton.betterinfo.dll + 20753
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\cvolton.betterinfo\cvolton.betterinfo.dll + 1f074
 - 0134384F
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 3cfde
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 3c934
 - 0134384F
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 38242
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 33df4
 - 0134384F
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 7ac5
 - 0134384F
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\mat.run-info\mat.run-info.dll + 54aa
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\mat.run-info\mat.run-info.dll + 12a4
 - 0134384F
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 2dc3ce
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 255d71
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 8f484 (cocos2d::CCActionInterval::step + 180)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 91564 (cocos2d::CCActionManager::update + 116)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 106e02 (cocos2d::CCScheduler::update + 82)
 - 01342536
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 3bb96
 - 01342357
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 320e6
 - 01342357
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\zilko.xdbot\zilko.xdbot.dll + 3d66
 - 01342357
 - 01342357
 - E:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - E:\SteamLibrary\steamapps\common\Geometry Dash\Geode.dll + c6596 (gdMainHook + 406 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:58)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c6e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c3e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 1d829db0
EBX: 14ed9e01
ECX: 00000000
EDX: 00000002
EBP: 012ff168
ESP: 012ff15c
EDI: 00000000
ESI: 012ff198
EIP: 6e3bd36d

**Comment by Rustring** [comment]
U use Linux because I have the same problem

**Comment by Stronkkey** [comment]
A good ol' segfault is required for every c++ project. Do you have BetterInfo installed?
