### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by RifiGD** [maxnut/GDmenu#212]
was playing my start pos version of sakupen egg when all of the sudden it crashed, don't know what happened but i didn't lose any progress when crashing so here's the log i guess
[2024-02-01_10-38-03.log](https://github.com/maxnut/GDMegaOverlay/files/14127566/2024-02-01_10-38-03.log)

**Comment by MysticAx0lotl** [comment]
The startpos switcher is still a bit buggy it seems

**Comment by maxnut** [comment]
don't really know if this issue is still relevant on newer version. if it happens again open another issue
