### ISSUE TITLE
Crash logs

### ISSUE THREAD

**Issue by GMDMarvolent** [maxnut/GDmenu#220]
![05 02 2024_08 42 19_REC](https://github.com/maxnut/GDMegaOverlay/assets/158813841/ab4f1dbe-ac9f-4645-a604-bdfe0795c986)

**Comment by TabFox-log** [comment]
You should add the crash log to your already created issue, not a new one 😃

**Comment by Stronkkey** [comment]
Looks like an issue to do with json parsing. @maxnut you should put code that reads from json files in a try block and catch any errors, you already made this mistake in v1.4

**Comment by Stronkkey** [comment]
https://github.com/maxnut/GDMegaOverlay/blob/dcd3d8e424093134d29df24c5d1ec9888fcebf99/src/GUI/GUI.cpp#L296
https://github.com/maxnut/GDMegaOverlay/blob/dcd3d8e424093134d29df24c5d1ec9888fcebf99/src/GUI/GUI.cpp#L312
I think either of these lines are responsible for the crash. They are not inside a try block and there isn't any error checking done to see if the files are properly formatted.

**Comment by GMDMarvolent** [comment]
idk why but my cousin's laptop use the mod but it didnt crash?

**Comment by maxnut** [comment]
added checks in 0af9b8680289b36702f7d17ba8d036f174b5280c
