### ISSUE TITLE
It crash when a try to click start audio crash log in desc

### ISSUE THREAD

**Issue by tadolikepineapple** [maxnut/GDmenu#222]
it crashes when i try to click start audio
2024-02-06T14:54:14+0100
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.15
Loader Commit: d35b2de
Bindings Commit: 253a854
Installed mods: 6
Problems: 0

== Exception Information ==
Faulty Module: C:\Windows\System32\DriverStore\FileRepository\u0392837.inf_amd64_9a77fba04d783a0e\B392251\atioglxx.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 5470828C (atioglxx.dll + 1b828c (DllMain + 971548))
Number Parameters: 2

== Stack Trace ==
 - C:\Windows\System32\DriverStore\FileRepository\u0392837.inf_amd64_9a77fba04d783a0e\B392251\atioglxx.dll + 1b828c (DllMain + 971548)
 - C:\Windows\System32\DriverStore\FileRepository\u0392837.inf_amd64_9a77fba04d783a0e\B392251\atioglxx.dll + 1b29a0 (DllMain + 948784)
 - C:\Windows\System32\DriverStore\FileRepository\u0392837.inf_amd64_9a77fba04d783a0e\B392251\atioglxx.dll + 1b2c72 (DllMain + 949506)
 - 48000000
 - A00AD975
 - 9825484D
 - 400075F6
 - 08095300
 - 00010100
 - A8000000
 - 001C778B

== Register States ==
EAX: 00000002
EBX: 00000000
ECX: 00000004
EDX: 00000000
EBP: 0000006c
ESP: 0075f5c4
EDI: 00000000
ESI: 00000000
EIP: 5470828c

== Installed Mods ==
  | [v1.3.4] alphalaneous.integratedloquibot
x | [v1.3.3] geode.custom-keybinds
x | [v2.0.0-beta.15] geode.loader
  | [v1.2.3] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v2.3.0] maxnu.gd_mega_overlay

**Comment by tadolikepineapple** [comment]
i try with no mod

**Comment by ndashadd** [comment]
record showcase then clicks

**Comment by Stronkkey** [comment]
Do you have an AMD GPU? If you search "atioglxx" you can find a bunch of results about something similar. Basically, try updating your drivers.

**Comment by maxnut** [comment]
can you give more details? from what i can see from the crash log i can only assume your drivers are the problem

**Comment by MysticAx0lotl** [comment]
As others have said, update your GPU drivers. If the problem persists, feel free to reopen this issue

**Comment by tadolikepineapple** [comment]
ok thx
