### ISSUE TITLE
Tasbot not accurate

### ISSUE THREAD

**Issue by tadolikepineapple** [maxnut/GDmenu#226]
I die when i try to play my macro

**Comment by MysticAx0lotl** [comment]
It's a work in progress. If you're experiencing issues with it, please post a more detailed explanation of your issue in the Discussions tab or the Discord server

**Comment by maxnut** [comment]
i know what you mean by tasbot but this proves you are probably under the age of 10
anyways this is not a code issue lol

**Comment by tadolikepineapple** [comment]
i am not

**Comment by Stronkkey** [comment]
maxnut trying to make a decent macro bot (impossible)
