### ISSUE TITLE
"Best Run" feature does not register runs to 100%

### ISSUE THREAD

**Issue by nisyam-j** [maxnut/GDmenu#227]
when i use the "Best Run" feature, i usually use it with start positions/start position switches, but the problem is, when i do a run to 100%, it doesn't show that.
for example, let's say i do a run from 50% - 80%, it shows "Best Run: 50 - 80", but the next attempt for example, i do 50% - 100%, it still shows "Best Run: 50 - 80"

so basically it doesn't recognize that you did a run to 100%

**Comment by maxnut** [comment]
fixed in a3c74106ec96d953c9894e60fa4e298224591746
