### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by nisyam-j** [maxnut/GDmenu#228]
so i updated GDMO to 2.4.4, but then, when i restart the game, it crashes, i try to open the game, it crashes, so everytime i open the game, it crashes.
when i opened the game without the mod, it works fine, when i tried to reinstall it, it crashes again. 
idk if this is a problem on MY end, so please give feedback

Crash Log:
2024-02-09T07:30:19+0700
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.16
Loader Commit: 4f21162
Bindings Commit: c901cbb
Installed mods: 20
Problems: 0

== Exception Information ==
C++ Exception: class std::bad_optional_access("Bad optional access")
Faulty Mod: <Unknown>

== Stack Trace ==
 - C:\WINDOWS\System32\KERNELBASE.dll + 149472 (RaiseException + 98)
 - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll + 7e96 (CxxThrowException + 102)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 57fab
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 5983a
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 7df8c
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 79def
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 79c4b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 5416b (geode::ModStateFilter::handle + 91)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 79d47
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 3404e (geode::DefaultEventListenerPool::handle + 78)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 341ae (geode::Event::postFromMod + 30)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + f2905 (geode::ipc::IPCFilter::handle + 69813)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + e4862 (geode::ipc::IPCFilter::handle + 12306)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + e6161 (geode::ipc::IPCFilter::handle + 18705)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + e6bf3 (geode::ipc::IPCFilter::handle + 21411)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2da7f (geode::EventFilter<geode::ModInstallEvent>::setListener + 9967)
 - 01561B17
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + c65a6 (geode::utils::web::AsyncWebRequest::userAgent + 12406)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

== Register States ==
EAX: 00b9f100
EBX: 19930520
ECX: 00000003
EDX: 00000000
EBP: 00b9f158
ESP: 00b9f100
EDI: 606a5c94
ESI: 00b9f1bc
EIP: 767f9472

**Comment by TripleBaconn** [comment]
open through steam

**Comment by nisyam-j** [comment]
> open through steam

still the same

**Comment by maxnut** [comment]
fixed in 29030cb14bd1467b2910ffcc16e4ad2ce3e1fc56
