### ISSUE TITLE
Unnecessary if statement

### ISSUE THREAD

**Issue by Antosser** [maxnut/GDmenu#230]
https://github.com/maxnut/GDMegaOverlay/blame/1fb35e2a248a472693ceed1b713d18c422af1114/src/Macrobot/Record.cpp#L56

**Comment by Stronkkey** [comment]
https://stackoverflow.com/questions/1073157/zero-size-malloc
> The behaviour is implementation defined, you will receive either a NULL pointer or an address.

I am not sure how safe it is to pass a NULL pointer to the WideCharToMultiByte function. Regardless, you can simply return a empty string in the condition.
[It might be better to use an external library for conversion.](https://github.com/boostorg/nowide)

**Comment by maxnut** [comment]
removed them in 8c429bc32bda5a32615d0537d612d8463926180c because they were unused

**Comment by Stronkkey** [comment]
Why did you even add them in the first place?
