### ISSUE TITLE
Macro Bot Not Working

### ISSUE THREAD

**Issue by UnknownSkid** [maxnut/GDmenu#233]
i change to record and played stereo madness in practice mode
then pressed save
then changed to play
then loaded stereo madness
it told me it only loaded 4 inputs (clearly was more than 4)
and it didnt work

im on geode v2.0.0-beta.17
mod version v2.4.6

**Comment by maxnut** [comment]
can you make a recording? i cant really do much with this info since it seems to work just fine for everyone

**Comment by Stronkkey** [comment]
Send macro file + recording.
