### ISSUE TITLE
‘Hide Pause Menu’ doesn’t work

### ISSUE THREAD

**Issue by nisyam-j** [maxnut/GDmenu#234]
It just doesn’t hide the pause menu, i turn it on and the pause menu is still there, nothing much to say really

**Comment by maxnut** [comment]
what mods you got

**Comment by nisyam-j** [comment]
> what mods you got

turns out while i was messing around with the mods, i found out the problem so yeah, mb

if you want to know what the mods breaking “Hide Pause Menu” were, it was Globed, xdBot, and Click Sounds
