### ISSUE TITLE
cant open the menu

### ISSUE THREAD

**Issue by Angel03bt** [maxnut/GDmenu#235]
after trying other mods, megahack Pro, QLmod, OPenHAck, i put the toggle menu to "i" and thennn after uninstalling all mods, i cant open it again, only can toggle some mods like speed hack and noclicip, how can i fix this or even is possible to fix?

**Comment by maxnut** [comment]
what
idk reset your settings?

**Comment by brickyosu** [comment]
same i cant open it with tab (i have mega hack so im gonna try to uninstall it and see if it works)

**Comment by brickyosu** [comment]
ok ig gdmegaoverlay does not have mega hack support :( it only works w/o megahack

**Comment by maxnut** [comment]
> ok ig gdmegaoverlay does not have mega hack support :( it only works w/o megahack

no shit

**Comment by Angel03bt** [comment]
how do i reset my settings 💀

**Comment by Angel03bt** [comment]
nvm i just deleted System32

**Comment by MysticAx0lotl** [comment]
Since this thread seems to be going nowhere, and it's a support thread anyway, I will close it. @Angel03bt , please join the Discord server if you have any further issues
