### ISSUE TITLE
Safe mode not working

### ISSUE THREAD

**Issue by Someone68** [maxnut/GDmenu#237]
Just nocliped bloodbath w/ Auto Safe Mode on, it still counted. It said - Safe Mode - on the end screen, but I still got the demon achievement and it did update my progress on the servers.

Totally not cool dude!! I just lost my account!

I'm using OpenHack until this gets fixed.

**Comment by MysticAx0lotl** [comment]
> Totally not cool dude!! I just lost my account!

Did you seriously reset your whole account because you accidentally noclipped one level

**Comment by Angel03bt** [comment]
bro its just one level use another mod to put safe mode bruh 💀

**Comment by maxnut** [comment]
closing this since no info and cant seem to replicate
