### ISSUE TITLE
the auto deafen dosent do anything

### ISSUE THREAD

**Issue by PJTaity** [maxnut/GDmenu#240]
i dont know if its just the fact that i dont KNOW what it does but it dosent really effect my sound or do anything at all that i can notice
please help

**Comment by MysticAx0lotl** [comment]
Auto deafen is meant for use with Discord voice calls

**Comment by PJTaity** [comment]
Ahh ok I thought it meant the in game music
Thanks

**Comment by MysticAx0lotl** [comment]
No problem!
