### ISSUE TITLE
Clickpack Issue

### ISSUE THREAD

**Issue by arandomdude7** [maxnut/GDmenu#253]
When I Was Creating My Clickpack I Used .WAV Instead Of .wav which made gdmo think that its not a valid clickpack when it is
it occurs to be this whats causing the bug: `if (entry.is_regular_file() && (entry.path().extension() == ".wav"))` you could change to: `if (entry.is_regular_file() && (entry.path().extension().tolower() == ".wav"))` if it doesn't work then it's understandable because i use c# and not c++
incase it says it does not exist ```#include <ctype.h>``` or this ```#include <iostream>```
- > GD Version: 2.204
- > GDMO Version: 2.5.1

**Comment by maxnut** [comment]
fixed
