### ISSUE TITLE
Percentage Problem with fps bypass

### ISSUE THREAD

**Issue by Bacmnz** [maxnut/GDmenu#254]
I`m still having problems with the percentage using fps bypass even tho it supposedly was already fixed, Im in geode with the most recent version, can you fix it?

**Comment by Stronkkey** [comment]
I don't have a magic sphere to look into to see how the percentage is buggy without some kind of video.

**Comment by Bacmnz** [comment]
> I don't have a magic sphere to look into to see how the percentage is buggy without some kind of video.

ok, I will record a video now.

**Comment by Bacmnz** [comment]
So, this only happens in 2.2 levels or levels that were modified in 2.2 and it also happens in the oficial levels (dash), here´s the video: https://youtu.be/HoAMQ-tZdCc (I didn´t put the video here cause it was too big)

**Comment by Stronkkey** [comment]
> Blame Rob

 Not sure what would cause this, maybe the bypass is broken?

**Comment by Bacmnz** [comment]
> > Blame Rob
> 
> Not sure what would cause this, maybe the bypass is broken?

Maybe, do I reinstall the game and install geode again? Do you think that wil fix? And another thing, when I meant "FPS bypass" I wanted to say Physics bypass, sorry for saying it wrong.

**Comment by Bacmnz** [comment]
So, I reinstalled it without Geode or anything, just vanilla Geometry Dash and everything was fine, when I installed Geode everything was also perfectly normal, but when I installed the the GD mega overlay the bug happend, so ye, it comes from the physics bypass.

**Comment by LousyBook05** [comment]
i probably think it's an incompatibility with another mod

**Comment by Bacmnz** [comment]
> i probably think it's an incompatibility with another mod

No, cause the thing is that I instlalled only the Gd mega overlay and nothing more and it was already giving the problem.

**Comment by MysticAx0lotl** [comment]
@maxnut Has this been resolved? Should it be closed?

**Comment by maxnut** [comment]
idk i think so
