### ISSUE TITLE
So my gdmo is throwing me this error every single time i try to go into a level to record a macro

### ISSUE THREAD

**Issue by doo0415** [maxnut/GDmenu#256]
I'm on latest version of this time which is 2.5.2 It started when I downloaded the version this morning this is the error in txt https://1drv.ms/u/s!Al9BSJ_OAKz-jUzy3Gk-PzFPr3yH?e=2ATpHS pls help me

**Comment by maxnut** [comment]
there are 0 errors in the file you shared

**Comment by doo0415** [comment]
it said to report to developers as an error

**Comment by maxnut** [comment]
ok but there are 0 errors in that file

**Comment by thecatontheceiling** [comment]
highest IQ gdmo user
