### ISSUE TITLE
Crashes when turning on blur background.

### ISSUE THREAD

**Issue by Breelandthecat** [maxnut/GDmenu#263]
The game randomly crashes when enabling the blur background thing.

**Comment by arandomdude7** [comment]
Me Too

**Comment by maxnut** [comment]
crashlog? video?

**Comment by Amazeww** [comment]
> crashlog? video?

[2024-02-19_16-06-30.log](https://github.com/maxnut/GDMegaOverlay/files/14329947/2024-02-19_16-06-30.log)
here's the crashlog.

**Comment by Breelandthecat** [comment]
2024-02-19T06:38:01-0600
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "maxnu.gd_mega_overlay" mod. Please submit this crash report to its developers (maxnu & SpaghettDev) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.20
Loader Commit: 453fac9
Bindings Commit: 60e063e
Installed mods: 103
Problems: 1

== Exception Information ==
Faulty Module: E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll
Faulty Mod: maxnu.gd_mega_overlay
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 7BF99834 (maxnu.gd_mega_overlay.dll + 19834)
Number Parameters: 2

== Stack Trace ==
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 19834
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 8718f
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 86de9
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 89253
 - 1630072B
 - 162C20E9
 - E:\SteamLibrary\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 18e3b
 - 162C1F0B
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - E:\SteamLibrary\steamapps\common\Geometry Dash\Geode.dll + 16f4d4 (crashlog::setupPlatformHandlerPost + 3956)
 - E:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

== Register States ==
EAX: 00000000
EBX: 0118f46c
ECX: 0000002c
EDX: 014ca8ac
EBP: 0118f3e0
ESP: 0118f3c0
EDI: 29c9a198
ESI: 29116b74
EIP: 7bf99834

== Installed Mods ==
x | [v1.0.5] abb2k.backup
x | [v1.1.1] adyagd.godlikefaces
x | [v1.1.2] adyagd.ingamelistmod
x | [v1.1.1] alphalaneous.deathlink
x | [v1.0.1] alphalaneous.happy_textures
x | [v1.0.1] alphalaneous.hide
x | [v1.0.0] alphalaneous.playercolorselect
x | [v1.1.2] alphalaneous.projectedstars
x | [v1.0.2] arkane.dl-team-icons
x | [v1.1.0] b1rtek.gddlintegration
x | [v1.4.6] beat.click-sound
x | [v1.0.5] bitz.customprofiles
x | [v1.0.2] blueblock6.cleanstartpos
x | [v1.0.0] capeling.colored_level_info_bg
x | [v1.1.4] capeling.demons_in_garage_2.2
  | [v1.1.0] capeling.goodbye_unnecessary_buttons
x | [v1.1.4] capeling.icon_profile_2.2
x | [v1.1.4] cdc.more-hints
x | [v1.0.1] cj_link.fakemoderator
x | [v1.0.1] coderqc.gdswearfilter
x | [v1.0.2] colon.bumpscosity
  | [v2.0.1] colon.gd_in_2019
x | [v4.0.0] cvolton.betterinfo
  | [v1.1.2] dankmeme.globed2
  | [v1.1.1] dogotrigger.roulette
  | [v1.1.1] ekv.hidePauseMenuHack
x | [v1.0.0] ekv.save_on_level_page
x | [v1.0.0] elnexreal.auto_priority
  | [v1.2.2] elnexreal.copy_song_id
x | [v1.0.0] elnexreal.demonlistinfo
x | [v1.5.0] elohmrow.death_tracker
x | [v1.0.1] elsai.copyright_remover_for_main_levels
x | [v1.0.0] elsai.pause_menu_zoom
x | [v1.0.3] firee.GoldenBest
  | [v1.4.2] firee.PrismMenu
x | [v2.4.0] fleym.nongd
  | [v1.2.15] gdutilsdevs.gdutils
  | [v1.5.2] geode.custom-keybinds
  | [v1.5.0] geode.devtools
x | [v2.0.0-beta.20] geode.loader
x | [v1.6.1] geode.node-ids
  | [v1.5.0] geode.texture-loader
x | [v1.2.0] hiimjustin000.integrated_demonlist
  | [v6.3.1] hjfod.betteredit
x | [v1.0.5] hjfod.gdshare
x | [v1.0.5] hjfod.gmd-api
x | [v1.1.0] iristraa.spinoffsubtitles
x | [v1.0.1] itzkiba.elegant_rankings
x | [v1.1.1] itzkiba.formatted_platformer_time
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.0.0] izzy.i_hate_you_top_lists
x | [v1.0.0] izzy.practice_sync
x | [v1.0.0] jojo989.main_menu_bg_customizer
x | [v1.2.0] khronophobia.more_settings_button
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.1.3] mat.circle-tool
x | [v1.0.0] mat.reference-image
x | [v1.0.2] mat.run-info
x | [v1.1.0] mat.scroll-zoom
x | [v2.5.6] maxnu.gd_mega_overlay
x | [v1.0.0-beta.5] minemaker0430.gddp_integration
  | [v1.0.4-beta.13] muhammadgames.bettermenu
x | [v1.0.1] n.friends
x | [v1.0.3] n.level_pronouns
  | [v1.2.1] n.robtop-jumpscare
x | [v1.1.0] ninkaz.blending_glow
x | [v1.3.3] oatmealine.ids_integration
x | [v1.3.2] oatmealine.nlw_integration
  | [v1.2.0-beta.4] org.dogotrigger.deathreplay
x | [v1.1.0] polsk.level_quests
x | [v1.0.0] polsk.pause_settings
x | [v1.6.1] prevter.openhack
x | [v1.0.0] raydeeux.antilobotomy
x | [v1.0.0] raydeeux.likebaitexterminator
x | [v1.0.0] raydeeux.poofshowbutton
x | [v1.1.1] relative.mininextfree
  | [v1.2.1] shineua.minecraft_splash
  | [v1.0.4] skyward.no_robtop_logo
x | [v1.0.1] slammy333.save_button
  | [v1.6.2] spaghettdev.gd-roulette
x | [v2.6.0] techstudent10.discord_rich_presence
x | [v1.0.0] techstudent10.hide_locks
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.1.0] thesillydoggo.better_startpos_menu
  | [v1.1.4] TheSillyDoggo.Cheats
x | [v1.0.0] thesillydoggo.dialogue_handler
x | [v1.0.0] thesillydoggo.entersearch
  | [v2.1.0] TheSillyDoggo.GradientPages
x | [v1.2.0] thesillydoggo.moretags
  | [v1.1.1] TheSillyDoggo.StartposSwitcher
  | [v1.6.0] tpdea.betterpause-Better
x | [v1.0.0] tpdea.scroll_any_input
x | [v1.8.1] undefined0.gdtweaks
  | [v1.1.1] undefined0.minecraft_menu
x | [v1.1.2] uproxide.geodedevelopers
x | [v1.0.3] weebify.coins_in_pause_menu
x | [v1.1.2] weebify.jumpscare
x | [v1.0.2] weebify.level_info_in_pause_menu
x | [v1.0.2] weebify.restartbtn
  | [v1.0.0] xanii.freaky_mode
x | [v1.0.4] xanii.youtubers
  | [v1.4.7] zilko.xdbot
x | [v0.1.2] zohnannor.dark_mode

**Comment by Breelandthecat** [comment]
***The video is compressed because of the 10MB Limit, And it was way over at 88mb.***

https://github.com/maxnut/GDMegaOverlay/assets/136176622/b3666d6f-197a-44d0-b5a5-d9c513407dcf

**Comment by maxnut** [comment]
should be fixed now.
