### ISSUE TITLE
The hitboxes are black.

### ISSUE THREAD

**Issue by TripleBaconn** [maxnut/GDmenu#265]
Yeah, I was playing a level and I realised all the spike hitboxes are black. I wouldn't be too annoyed, but most levels have black spikes, and so botting is harder. Also the bot is inaccurate. No macros I've made HAVEN'T broken.

**Comment by LousyBook05** [comment]
i think it's a pc error

**Comment by Stronkkey** [comment]
Update graphics driver + skill issue.

**Comment by TripleBaconn** [comment]
> Update graphics driver + skill issue.

they are updated, idk why its only for me

**Comment by maxnut** [comment]
fixed in fdddcfaea11f1d2d60372db2bab6fcde7e759e1c
