### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Rustring** [maxnut/GDmenu#268]
Here is the log
[2024-02-20_21-30-01.log](https://github.com/maxnut/GDMegaOverlay/files/14348534/2024-02-20_21-30-01.log)

**Comment by maxnut** [comment]
ok but how did you crash

**Comment by Rustring** [comment]
![Screenshot_20240221_212635](https://github.com/maxnut/GDMegaOverlay/assets/155897302/8c409256-0c26-43d1-8181-ab9f7e0840a5)
Also I deleted OpenHack but the issue still persists

**Comment by Rustring** [comment]
Not sure if I am can ask this here but how to disable the blur in saved.json file? I can't find it.

**Comment by ART-007-25** [comment]
Same problem here, even with a clean Proton-prefix and reinstalling both the game and Geode, game crashes when the progress bar reaches 100%. It seems @Rustring is also on Linux, using Proton. I have multiple crash logs, but unfortunately, none of them seem to show anything useful. And there is no error message for me. It just crashes silently.

On Fedora 39, KDE. Overriding the individual DLLs found from the unpacked MegaOverlay does not work.

**Comment by maxnut** [comment]
> Same problem here, even with a clean Proton-prefix and reinstalling both the game and Geode, game crashes when the progress bar reaches 100%. It seems @Rustring is also on Linux, using Proton. I have multiple crash logs, but unfortunately, none of them seem to show anything useful. And there is no error message for me. It just crashes silently.
> 
> On Fedora 39, KDE. Overriding the individual DLLs found from the unpacked MegaOverlay does not work.

this crash seems to be caused by the blur shader compiling, as i've confirmed with @Rustring. can you both share some info about your systems, and also see if linux supports whatever shader i'm compiling?

**Comment by su226** [comment]
I have 1 desktop and 1 laptop both running ArchLinux.

- Desktop AMD Radeon RX 5700 XT with open-source drivers (mesa) ✗
- Desktop AMD Radeon RX 5700 XT with proprietary drivers (amdgpu-pro) ✗
- Laptop AMD Ryzen 9 7945HX (iGPU) with open-source drivers (mesa) ✗
- Laptop NVIDIA RTX 4060 with proprietary drivers ✓

It seems on my machines only NVIDIA graphics works.

**Comment by maxnut** [comment]
ive made the shader compilation optional for now, since i dont know how to prevent this crash.
