### ISSUE TITLE
Hitboxes are gone when entering into gravity portals (v2.5.8)

### ISSUE THREAD

**Issue by Lolikarbuzik** [maxnut/GDmenu#270]
so when you enter a lot of gravity portals in a small time frame the hitboxes are just gone and you have to restart the level again (leave and play again)

you can try it yourself with this level: 101264473

**Comment by Lolikarbuzik** [comment]
https://github.com/maxnut/GDMegaOverlay/assets/73756261/c728d63d-bd0c-44f6-8747-c1b205dc5aa7

**Comment by Lolikarbuzik** [comment]
> so when you enter a lot of gravity portals in a small time frame the hitboxes are just gone and you have to restart the level again (leave and play again)
> 
> you can try it yourself with this level: 101264473

This bug actually works only when you change the gravity really fast

**Comment by maxnut** [comment]
does this also happen with vanilla gd?

**Comment by Lolikarbuzik** [comment]
> does this also happen with vanilla gd?

No only when using gdmo hitboxes

**Comment by maxnut** [comment]
works fine even with the level you provided.
