### ISSUE TITLE
Total clicks counter in the CPS module counts 1 click as 2 in dual mode

### ISSUE THREAD

**Issue by flyingturt1e** [maxnut/GDmenu#277]
The total click counter in the CPS module increases by 2 with every click when dual mode is enabled

For example: there are 5 clicks in this clip, but the total click counter counts 10 total clicks. The CPS counter is not affected though, just the total

https://github.com/maxnut/GDMegaOverlay/assets/91761140/36a51422-a95b-449a-bdc9-8b5961cb2e1a

**Comment by MysticAx0lotl** [comment]
Wow, someone actually using the issues tab correctly (impossible)

**Comment by maxnut** [comment]
forgot i fixed this
