### ISSUE TITLE
the GUI isnt showing up when i press tab

### ISSUE THREAD

**Issue by thefreefallingladder** [maxnut/GDmenu#281]
how do i fix this issue because i want to test the macro i made yesterday

**Comment by Void-666** [comment]
if you use other mod menus:
1. disable other mod menus that use tab key to open
2. change key to open gdmo to any free key
3. now you can reenable other menus

**Comment by thefreefallingladder** [comment]
Thanks for the solutions but how do i change the open key with something
else without using the menu itself (im not too experienced with editing
files and stuff)

**Comment by Void-666** [comment]
do you use other menus?

**Comment by thefreefallingladder** [comment]
No
Any other mods i use just adds more stuff to the already existing UI of gd

**Comment by maxnut** [comment]
is the mod loaded

**Comment by thefreefallingladder** [comment]
I dont know
All i know is that its turned on and the menu wont show up when i press tab

**Comment by maxnut** [comment]
you can check in geode, do that

**Comment by thefreefallingladder** [comment]
Ive already checked everything but it still isnt working properly
Can you tell me how to rebind the key to something else?

**Comment by maxnut** [comment]
you cant rebind without opening the menu, plus rebinding would not do anything unless your tab is broken, you clearly have another problem

**Comment by thefreefallingladder** [comment]
Well what do i do to fix this then?

**Comment by maxnut** [comment]
how am i supposed to know, read your mind?! ur not providing any information. also move from github and make a post on the discord, i will close the issue since it's inconvenient to discuss here
