### ISSUE TITLE
Macro Playback Not Working

### ISSUE THREAD

**Issue by hypnOX22** [maxnut/GDmenu#283]
So, I was testing a wave thing I was doing and I was recording the macro at 0.05 speed (with fps/physics bypass of 1000 fps don't ask) and I turn on normal speed to see it in real time. When I hit play, no inputs happen. I just run into the wall. Any idea of what's going on?

**Comment by maxnut** [comment]
check how many inputs were actually in the macro

**Comment by maxnut** [comment]
closed because can't replicate and got no further info
