### ISSUE TITLE
Hide pause button does not hide the pause button

### ISSUE THREAD

**Issue by TV46** [maxnut/GDmenu#284]
self explanatory

**Comment by maxnut** [comment]
mod list

**Comment by TV46** [comment]
What?

**Comment by maxnut** [comment]
what mods are you using

**Comment by TV46** [comment]
Ok
- geode 
- autosong 
- Backup
- Better edit
- Better pause
- Better info
- Circle tool
- Clean startpos 
- Coloured icon kit
- Compact lists
- custom keybinds
- Custom profiles
- Enter search
- GD tweaks
- GD mega overlay
- GD share
- GD utils 
- Globed
- GMD api
- Godlikefaces
- icon save 2.2
- Icon profile 2.2
- Integrated demon list
- Music manager
- Node IDs
- Restart buttons
- Scroll zoom
- Texture loader
- Visible checkpoints

**Comment by TV46** [comment]
Sorry it’s a long list

**Comment by Error-Cezar** [comment]
dump, same issue

**Comment by TV46** [comment]
Dump?

**Comment by Error-Cezar** [comment]
I meant bump I'm stupid

**Comment by maxnut** [comment]
should be fixed in f984362ef27bc99756c8501192ac89172f103748
