### ISSUE TITLE
Hitbox multiplier doesn't work with hazards

### ISSUE THREAD

**Issue by Void-666** [maxnut/GDmenu#285]
Screentshot:
![20240301165346_1](https://github.com/maxnut/GDMegaOverlay/assets/77442200/90092059-fa6d-4db4-9eb8-b3eda599aa22)

**Comment by maxnut** [comment]
it seems to only be working partially ill look into it

**Comment by maxnut** [comment]
fixed in fdddcfaea11f1d2d60372db2bab6fcde7e759e1c
