### ISSUE TITLE
In-game (vanilla) hitboxes don't work

### ISSUE THREAD

**Issue by TheIndus** [maxnut/GDmenu#286]
Used the editor hitboxes option and it's always disabled with this mod on even I turned the hitbox checkbox on. Practice mode hitboxes don't work like in the editor too. 

The black spike hitboxes really annoy me when I turned the hitboxes on since most levels have black spikes so I just want to use the in-game one.

**Comment by maxnut** [comment]
black hitboxes are a bug. mind sharing your saved.json file?

**Comment by TripleBaconn** [comment]
> black hitboxes are a bug. mind sharing your saved.json file?

im not him, but i have the same issue aswell
[saved.json](https://github.com/maxnut/GDMegaOverlay/files/14465370/saved.json)

**Comment by TheIndus** [comment]
Here
[saved.json](https://github.com/maxnut/GDMegaOverlay/files/14467826/saved.json)

**Comment by TheIndus** [comment]
> black hitboxes are a bug. mind sharing your saved.json file?

Here
[saved.json](https://github.com/maxnut/GDMegaOverlay/files/14467826/saved.json)

**Comment by maxnut** [comment]
fixed in fdddcfaea11f1d2d60372db2bab6fcde7e759e1c
