### ISSUE TITLE
render broken

### ISSUE THREAD

**Issue by tadolikepineapple** [maxnut/GDmenu#287]
when i try to render the rendered vid is WIDE

**Comment by tadolikepineapple** [comment]
![Capture d'écran 2024-03-01 140251](https://github.com/maxnut/GDMegaOverlay/assets/155880789/638f9421-e4b2-4bb6-9542-092e81445842)

**Comment by TripleBaconn** [comment]
its because your monitor isnt 16:9

**Comment by maxnut** [comment]
what resolution are you rendering at

**Comment by maxnut** [comment]
solved in the discord
