### ISSUE TITLE
instant complete dowsnt work

### ISSUE THREAD

**Issue by nubd7** [maxnut/GDmenu#288]

**Comment by maxnut** [comment]
it does tho

**Comment by nubd7** [comment]
Ill try again

**Comment by maxnut** [comment]
ohh I know what you mean
it doesn't work in rated levels because of anticheat, I need to make anticheat bypass

**Comment by nubd7** [comment]
yea i tried in my level it worked but like ispywithmylittloeeye it didnt
thanks btw
