### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ethanmejia** [maxnut/GDmenu#290]
If you load a platformer level with layout mode on the game crashes.

**Comment by maxnut** [comment]
can you tell me which level? i tried and it works fine.

**Comment by Ethanmejia** [comment]
I tried loading the the secret hollow level.

**Comment by Ethanmejia** [comment]
I also beat the previous level with layout mode on and some weird things happened. The camera froze but you could play the level as normal. The only way I could do this was with show hitboxes.

**Comment by maxnut** [comment]
this crash should be fixed
