### ISSUE TITLE
icon size bug

### ISSUE THREAD

**Issue by TripleBaconn** [maxnut/GDmenu#291]
was recording a macro, when i was a mini and died, i respawned with a big icon but small hitbox

**Comment by maxnut** [comment]
send your settings (save folder / saved.json) and what level were u playing. cant seem to replicate

**Comment by TripleBaconn** [comment]
level: recirculation and sakupen end (both by nick240)
[saved.json](https://github.com/maxnut/GDMegaOverlay/files/14483521/saved.json)
[settings.json](https://github.com/maxnut/GDMegaOverlay/files/14483523/settings.json)

**Comment by TripleBaconn** [comment]
Mod list (sorry if long:

- Geode
- A daily Shop
- accurate practice attempts
- auto priority to high
- backup
- betteredit
- betterpause
- betterinfo
- changefont19
- colored icon kit
- copyright remover for mail levels
- compact lists(disabled)
- crystal client(disabled)
- custom keybinds
- dark mode
- devtools
- death tracker
- death markers
- editor save button (disabled)
- emojis in comments
- fakemoderator
- gamemode swapper
- gddp integration
- gd mega overlay
- gdshare
- gddl integration
- globed
- gmd api
- godlikfaces
- icon freeze
- icon save 2.2
- id hyperlinks
- integrated demonlist
- integrated loquibot
- jukebox
- level info
- level thumbnails
- main level pages
- minecraft! (disabled)
- moregames
- node ids
- openhack (disabled)
- prism menu(disabled)
- qolmod(disabled)
- restart buttons
- sceneswitcher
- startpos switcher
- texture loader
- unlisted objects in editor
- unixsync
- usable explorers
- visiblecheckpoints
- volume scroll
- wave trail drag fix
- xdbot
- zcb live

**Comment by TripleBaconn** [comment]
https://youtu.be/TiVhMBKtHV0

**Comment by TripleBaconn** [comment]
It appears to be fixed in 2.7.3
