### ISSUE TITLE
Physics bypass not working for values below 240

### ISSUE THREAD

**Issue by MainConMan** [maxnut/GDmenu#297]
For example, setting physics bypass to 60 results in the game playing like it's set to 240, 90 like it's set to 270, 150 like it's set to 300, I used a tps counter level to test. 
[tps counter.zip](https://github.com/maxnut/GDMegaOverlay/files/14532882/tps.counter.zip)

**Comment by maxnut** [comment]
not true clearly. just put your fps to 30 and see for yourself
