### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by nubd7** [maxnut/GDmenu#298]
gd keeps crashing evrytime i open[
![image_2024-03-09_102405034](https://github.com/maxnut/GDMegaOverlay/assets/161943904/c1f4c6dd-119b-4747-abec-37f1e4a62e91)
](url)

**Comment by Rustring** [comment]
Since which version it has been happening?

**Comment by nubd7** [comment]
.3 works fine but .4 and .5 dont work

**Comment by Rustring** [comment]
Ok I am on my own modification of GDMO witch is still on 2.7.3 and I will try to see if this crash occurs on my end once I update it, also what options you have enabled that can cause this.

**Comment by nubd7** [comment]
I have noclip and all bypasses on

**Comment by MysticAx0lotl** [comment]
Closed due to lack of information, inactivity, and OP spamming issues
