### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by bimbifan** [maxnut/GDmenu#299]
When I verify my level in layout mode I get the following:

2024-03-09T16:05:50+0300
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.21
Loader Commit: 06afbb8
Bindings Commit: ff44163
Installed mods: 6
Problems: 0

== Exception Information ==
C++ Exception: class std::out_of_range("invalid vector subscript")
Faulty Mod: <Unknown>

== Stack Trace ==
 - C:\Windows\System32\KERNELBASE.dll + 12ca42 (RaiseException + 98)
 - C:\Windows\SYSTEM32\VCRUNTIME140.dll + 7e96 (CxxThrowException + 102)
 - C:\Windows\SYSTEM32\MSVCP140.dll + 2d11f (std::_Xout_of_range + 31)
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 100ca
 - 0BEF0697
 - 0BEF2556
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 737ca
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 69f9b
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 521fd
 - 0C052996
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + d3eaf
 - 01122D76
 - 01122B97
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 7b6e2
 - 01122B97
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 54ffe
 - 01122B97
 - C:\Program Files (x86)\Geometry Dash\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - C:\Program Files (x86)\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Geometry Dash\Geode.dll + 16e444 (gdMainHook + 532 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:59)
 - C:\Program Files (x86)\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 1fa29 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67a9e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\Windows\SYSTEM32\ntdll.dll + 67a6e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 001aef10
EBX: 19930520
ECX: 00000003
EDX: 00000000
EBP: 001aef68
ESP: 001aef10
EDI: 74c31a94
ESI: 00000029
EIP: 7626ca42

== Installed Mods ==
x | [v1.3.1] dankmeme.globed2
x | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.21] geode.loader
x | [v1.7.1] geode.node-ids
x | [v2.7.5] maxnu.gd_mega_overlay
x | [v4.0.0] user95401.mainlevelseditor

**Comment by maxnut** [comment]
fixed
