### ISSUE TITLE
Auto Deafen does not work on call.

### ISSUE THREAD

**Issue by RxAttacker** [maxnut/GDmenu#303]
It does not deafen when using hotkey or and going over 50% (You set the % in which is it meant to auto deafen. I turned on DRP and still it does not work.

**Comment by maxnut** [comment]
did you set the shortcut in discord?
you have to set the shortcut as alt + deafen key

**Comment by RxAttacker** [comment]
I mean my shortcut on discord is ctrl shift D, do i have to set it as the same on GDMO? Also what about Auto Deafen when you hit the % set.

**Comment by maxnut** [comment]
i literally Stated that the shortcut **must** be alt + the gdmo deafen key. so if you set the deafen key as n in gdmo, set the shortcut in discord as alt + n
