### ISSUE TITLE
crush

### ISSUE THREAD

**Issue by bimbifan** [maxnut/GDmenu#306]
2024-03-11T18:34:41+0300
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "maxnu.gd_mega_overlay" mod. Please submit this crash report to its developers (maxnu, SpaghettDev) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.22
Loader Commit: d90bfdd
Bindings Commit: 179edb2
Installed mods: 7
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll
Faulty Mod: maxnu.gd_mega_overlay
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 6ED4BB71 (maxnu.gd_mega_overlay.dll + 6bb71)
Number Parameters: 2

== Stack Trace ==
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 6bb71
 - 033F25D7
 - 033F0AB6
 - 033F08D7
 - C:\Program Files (x86)\Geometry Dash\libcocos2d.dll + 106ec4 (cocos2d::CCScheduler::update + 276)
 - 01383196
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 53146
 - 01382FB7
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 3a6d6
 - 01382FB7
 - 033D0409
 - 033D022B
 - C:\Program Files (x86)\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Geometry Dash\Geode.dll + 16f8c4 (crashlog::setupPlatformHandlerPost + 3956)
 - C:\Program Files (x86)\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 1fa29 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67a9e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\Windows\SYSTEM32\ntdll.dll + 67a6e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 00000000
EBX: 00000000
ECX: 5e9e3941
EDX: 00f2acc3
EBP: 00cff7f4
ESP: 00cff7e8
EDI: 19c6d050
ESI: 19c6d050
EIP: 6ed4bb71

== Installed Mods ==
x | [v1.3.2] dankmeme.globed2
x | [v1.5.2] geode.custom-keybinds
x | [v1.5.1] geode.devtools
x | [v2.0.0-beta.22] geode.loader
x | [v1.8.0] geode.node-ids
x | [v2.8.0] maxnu.gd_mega_overlay
x | [v4.0.0] user95401.mainlevelseditor

**Comment by maxnut** [comment]
don't open issues for every single crashlog you get
