### ISSUE TITLE
crush

### ISSUE THREAD

**Issue by bimbifan** [maxnut/GDmenu#307]
2024-03-11T19:01:54+0300
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.22
Loader Commit: d90bfdd
Bindings Commit: 179edb2
Installed mods: 8
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Geometry Dash\libcocos2d.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 72E1DAEA (libcocos2d.dll + 6daea (cocos2d::CCDrawNode::drawPolygon + 1146))
Number Parameters: 2

== Stack Trace ==
 - C:\Program Files (x86)\Geometry Dash\libcocos2d.dll + 6daea (cocos2d::CCDrawNode::drawPolygon + 1146)
 - 0C1A31F6
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 4c822
 - 0C1A3027
 - C:\Program Files (x86)\Geometry Dash\GeometryDash.exe + 198e17
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 4eae9
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 4c7a1
 - 0C1A0A77
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 47c67
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 46526
 - 0C1A0A77
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 3821b
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 36806
 - 0C1A0A77
 - 0C1B0C56
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 8e438
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 88d86
 - 0C1B0A77
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 6bb91
 - 0C1B0A77
 - 014A3196
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 53146
 - 014A2FB7
 - C:\Program Files (x86)\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 3a6d6
 - 014A2FB7
 - C:\Program Files (x86)\Geometry Dash\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - C:\Program Files (x86)\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Geometry Dash\Geode.dll + 16f8c4 (crashlog::setupPlatformHandlerPost + 3956)
 - C:\Program Files (x86)\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 1fa29 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67a9e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\Windows\SYSTEM32\ntdll.dll + 67a6e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 00000032
EBX: 00f3f3d4
ECX: 00f3f338
EDX: 00000000
EBP: 00f3f1d0
ESP: 00f3f074
EDI: 00f3f31c
ESI: 027fffd8
EIP: 72e1daea

== Installed Mods ==
x | [v1.3.2] dankmeme.globed2
x | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.22] geode.loader
x | [v1.8.0] geode.node-ids
x | [v1.0.2] mat.run-info
x | [v2.8.0] maxnu.gd_mega_overlay
x | [v1.1.0] uproxide.autosong
x | [v4.0.0] user95401.mainlevelseditor

**Comment by maxnut** [comment]
I'm gonna crush your skull if you dont give more info, crashlogs are pretty much useless

**Comment by MysticAx0lotl** [comment]
Closed due to lack of info
