### ISSUE TITLE
Title Gradient removes folding arrow

### ISSUE THREAD

**Issue by Nebularzz** [maxnut/GDmenu#310]
Enabling the Title Gradient hack removes the arrow that folds the menu, but it doesn't get rid of it's functionality. It's just visual.

Without Title Gradient:
![image](https://github.com/maxnut/GDMegaOverlay/assets/103582504/61656fc7-fc10-4ef1-bbad-662dc2841c27)

With Title Gradient:
![image](https://github.com/maxnut/GDMegaOverlay/assets/103582504/5e392dc1-4144-455e-ae3a-811223326370)

**Comment by maxnut** [comment]
ye i know cant do much about it other than reimplement it since im rendering over the imgui titlebar :/ sorry

**Comment by maxnut** [comment]
actully nevermind, fixed in c862b7d3033e3ab6f45d6a85e77c4ca75e8800c4
