### ISSUE TITLE
Drop Shadow and Blur Background are incompatible

### ISSUE THREAD

**Issue by Nebularzz** [maxnut/GDmenu#311]
Very questionable things happen when you enable both at the same time.
But for some reason, enabling Blur GD gets rid of the weird effect that happens.
Edit: Title Gradient also gets rid of the weird effect.

https://github.com/maxnut/GDMegaOverlay/assets/103582504/255b0048-c50a-4fc7-b9fe-f41de1e40760

**Comment by maxnut** [comment]
dang i didnt notice that will fix

**Comment by maxnut** [comment]
fixed in 33dc4c4c91eca777bfde9fc4f03b94827af4c6f5
