### ISSUE TITLE
Recording macros not working properly with speedhack

### ISSUE THREAD

**Issue by jesperhetprootje** [maxnut/GDmenu#312]
When i use speedhack while recording a macro, it works fine, but when i play the macro it plays the inputs in the real time i played it, so if i held for 1 second (with speedhack on for example 0.5), then played it on normal speed, it still holds for 1 second, while it should hold for 0.5 seconds because i recorded it with speedhack on 0.5. Now something unrelated, but still useful to add: more accurate practice mode. This is because i am trying to bot the top 25 of the demonlist, but thats not possible when practice mode is even a little inaccurate.

**Comment by maxnut** [comment]
both info are wrong??? bro what bot are you using 💀

jokes aside maybe its a mod incompatibility, the bot works fine with speedhack and i have no issues botting levels like acheron or even kyouki. if the bug persists disable everything and maybe join the discord to share some more info
