### ISSUE TITLE
replaybot broken

### ISSUE THREAD

**Issue by ReviD11** [maxnut/GDmenu#320]
https://drive.google.com/file/d/1y7fUtjkDeuCApf7z-b4WOaohAuUbEcQm/view?usp=drive_link

The video link

if i try to play a macro it just does not work.

**Comment by maxnut** [comment]
i don't have access to the file

**Comment by ReviD11** [comment]
are u that triplebacon?

**Comment by ReviD11** [comment]
because i accidently declined that request.

**Comment by ReviD11** [comment]
wait it should be working now.

**Comment by maxnut** [comment]
you restarted the level while recording bruh. toggle playing before restarting otherwise inputs will be cleared
