### ISSUE TITLE
[BUG] - Show Hitbox disapears on certain parts

### ISSUE THREAD

**Issue by Error-Cezar** [maxnut/GDmenu#323]
Don't really know how to explain it, but sometimes when you pass certain parts of a level whatever your settings are, your hitboxes just disapears 

Check video for reference

https://github.com/maxnut/GDMegaOverlay/assets/64325581/770b725a-f2d9-4390-8a52-36630ce9befc

**Comment by maxnut** [comment]
its fixed in the latest update.

**Comment by Error-Cezar** [comment]
I just noticed that, I was going to close the issue in anyway

Thanks for confirming tho
