### ISSUE TITLE
Moving a lot of objects makes the game crash

### ISSUE THREAD

**Issue by Nearth22** [maxnut/GDmenu#324]
I spent over 5 hours (I'm not kidding) making a level. However, I noticed the level was too close to the ground, so I decided to select all objects and move them up. Unfortunately, the game crashed, and I LOST EVERYTHING. All my hard work and half of the level were just deleted. I can rebuild it again, but it's painful to spend another 5 hours on something I had already done, all because of a bug. Please fix it.

Note: I was using the "no respawn blink" option and I wasn't using any other mods.

**Comment by Nearth22** [comment]
Also, the game crashed when I pressed the button to move up with all objects selected. Selecting the objects didn't cause the game to crash.

**Comment by MysticAx0lotl** [comment]
That seems like a vanilla issue, since that's happened to me with other mods like BetterEdit and with no mods at all

**Comment by Nearth22** [comment]
It's really a vanilla issue, unrelated to GDMO, as this happened to me again without having any active mods (at least I saved before the game crashed).
Thanks MysticAx0lotl for the response.
