### ISSUE TITLE
Gd mega overlay not opening

### ISSUE THREAD

**Issue by Marcoiscool123** [maxnut/GDmenu#326]
I uninstalled every  single mod execpt node ids and guess what its not opening i will so you the error.
![image](https://github.com/maxnut/GDMegaOverlay/assets/163798559/8c6cfebc-3729-4ca1-a275-d343166f81fa)

**Comment by Nebularzz** [comment]
Seems like a corrupted savefile. Try deleting these files in %localappdata%\GeometryDash\geode\mods\maxnu.gd_mega_overlay (you will lose your gdmo settings): saved.json, settings.json, shortcuts.json, windows.json

**Comment by Gd73762648** [comment]
I have the same issue with the game crashing when i play when I set the fps to 3 with 333 zeros

**Comment by Nebularzz** [comment]
> I have the same issue with the game crashing when i play when I set the fps to 3 with 333 zeros

You're not supposed to do that though.
Your PC wouldn't be able to handle that anyway.
