### ISSUE TITLE
conflicts with node-ids

### ISSUE THREAD

**Issue by ghost** [maxnut/GDmenu#334]
when i open gd is crashes. at random I found out that this is to blame node-ids

**Comment by maxnut** [comment]
not true, its another mod or something else. try deleting your settings

**Comment by VoidOreos** [comment]
i too started crashing at launch after installing node ids, I've deleted the game deleted and reinstalled geode, deleted all files from gd and repaired them on steam and it still crashes on launch. i have a crash report screenshotted if that would help

**Comment by VoidOreos** [comment]
> when i open gd is crashes. at random I found out that this is to blame node-ids

I figured it out go to browse local game files from steam and find the geode folder from there go to the mods folder and delete node ids, once you delete node ids you can now launch the game however you aren't done go to geode tab on gd and uninstall gd mega overlay and reinstall it, this will fix whatever issue was going on however it will delete anything saved in your gd mega overlay menu meaning you lose all recorded maps and previous setting applied, i honestly don't know what caused the issue i just thought id post a fix

**Comment by ghost** [comment]
> > when i open gd is crashes. at random I found out that this is to blame node-ids
> 
> I figured it out go to browse local game files from steam and find the geode folder from there go to the mods folder and delete node ids, once you delete node ids you can now launch the game however you aren't done go to geode tab on gd and uninstall gd mega overlay and reinstall it, this will fix whatever issue was going on however it will delete anything saved in your gd mega overlay menu meaning you lose all recorded maps and previous setting applied, i honestly don't know what caused the issue i just thought id post a fix

Thx you VoidOteos

**Comment by maxnut** [comment]
cant replicate, seems like an issue with node ids
