### ISSUE TITLE
smart startpos?

### ISSUE THREAD

**Issue by ghost** [maxnut/GDmenu#337]
in the menu i can't find any smart startpos switcher but its very annoying to practice levels because I have to use practice mode. But there are no other mods I can find to get smart startpos but the level im trying to play requires smart startpos.

**Comment by OndaBenZolterr** [comment]
Startpos switcher, use arrow keys <- and -> to switch....

**Comment by HumaanK** [comment]
theres already a mod for that on geode

**Comment by maxnut** [comment]
not the place for this
