### ISSUE TITLE
click sound

### ISSUE THREAD

**Issue by TheSpat** [maxnut/GDmenu#341]
### The program cannot find the click pack although it is there
![image](https://github.com/maxnut/GDMegaOverlay/assets/165073928/5528c17f-8b73-4d8a-9ed3-92c3e9ed3d23)

![image](https://github.com/maxnut/GDMegaOverlay/assets/165073928/b9bf39d6-bad9-40b3-916a-59c1d5bd643d)

**Comment by maxnut** [comment]
it can find it but its not valid check a valid clickpack for the correct format
