### ISSUE TITLE
[Feature request] Custom modifiable bind to open the menu.

### ISSUE THREAD

**Issue by HumaanK** [maxnut/GDmenu#342]
can you add a option for a custom bind to open the menu in the mod settings

**Comment by HumaanK** [comment]
Ignore my other message. I prorpose the integration of a setting in the mod settings / main settings that lets you customize the key you press to open the menu. Since I play on the Steam Deck, I am not able to press the 'tab' key. Adding this requested feature will enable me to actually be able to use the client. Have a nice day!

**Comment by maxnut** [comment]
not the place to suggest, join the discord
