### ISSUE TITLE
ADD A HACK THAT REMOVES THE SHIP TRAIL ENTIRELY

### ISSUE THREAD

**Issue by WaitWhat1981** [maxnut/GDmenu#344]
most "megahacks" contain it and it would make removing your ship trail (and ufo) easier

**Comment by HumaanK** [comment]
This can already be done without hacks via game texture manipulation. It's miles easier and there are plenty of YouTube tutorials for removing the ship trail and other things. Just search 'how to remove ship trail' on YouTube and the tutorial by Flub is the most useful. Hope I could help!

**Comment by HumaanK** [comment]
Just to let you know, the same tutorial by Flub also has a ship particle removal tutorial aswell if you also want that.
