### ISSUE TITLE
loading resources freezes when launching GD

### ISSUE THREAD

**Issue by janekt2000** [maxnut/GDmenu#350]
there is nothing to describe

**Comment by maxnut** [comment]
maybe the fps is set to 0 try deleting the settings by holding shift when starting gd and uninstalling gdmo

**Comment by janekt2000** [comment]
> maybe the fps is set to 0 try deleting the settings by holding shift when starting gd and uninstalling gdmo

didnt work

**Comment by maxnut** [comment]
did you delete all settings when you uninstalled

**Comment by janekt2000** [comment]
> did you delete all settings when you uninstalled

how do you delete settings

**Comment by maxnut** [comment]
when you uninstall the mod it asks if you wanna also delete all settings

**Comment by janekt2000** [comment]
thanks but this time i reinstalled and everything worked

**Comment by janekt2000** [comment]
> when you uninstall the mod it asks if you wanna also delete all settings

i know the reason why it didnt load i turned on speed hack that is very slow
