### ISSUE TITLE
Inaccurate FPS display

### ISSUE THREAD

**Issue by edwloef** [maxnut/GDmenu#361]
Comparing the in-game FPS counter with the one included in the menu, the menu one seems to always be slightly off. In this clip my FPS are capped at 240, despite that the menu's counter rests at 239. After looking into `Commmon::calculateFramerate()` I can't find any issue though.

https://github.com/maxnut/GDMegaOverlay/assets/75493688/cedff890-04b5-471c-9128-50e3d2172872

**Comment by maxnut** [comment]
first of all calculate framerate is not responsible for the label, you need to look into labels implementation. the fps counter being off is probably because its averaging and rounding incorrectly shouldn't be too hard to fix

**Comment by maxnut** [comment]
fixed
