### ISSUE TITLE
Adding click sounds aren't possible anymore

### ISSUE THREAD

**Issue by TypicalOven** [maxnut/GDmenu#367]
I noticed that there are no presets found in the click sounds module, in the previous base game update. There seems to be 2 click packs named "Mouse" and "Num0," so I tried adding that same folder to the unzipped directory, this goes for the only three folders of the client. Is there still a way to add click sounds in the latest update?  
![image](https://github.com/maxnut/GDMegaOverlay/assets/88714894/881e78fe-3ab1-4352-a83a-ca21756bb0d7)

**Comment by maxnut** [comment]
move them to save folder -> clickpacks

**Comment by TypicalOven** [comment]
may i ask where's the save folder located?
