### ISSUE TITLE
Crashes With Geode Beta 26

### ISSUE THREAD

**Issue by ghost** [maxnut/GDmenu#368]
Launch then crash, works when disabling this mod:
`2024-05-09T17:07:08+0200
Ouch. That hurt :(

== Geode Information ==
- Working Directory: C:\Program Files (x86)\Geometry Dash v2.204a\Geometry.Dash.v2.204a
- Loader Version: v2.0.0-beta.26 (Geometry Dash v2.204)
- Loader Commit: 2857ecf
- Bindings Commit: d35e301
- Installed Mods: 29 (Loaded: 8/26)
- 4GB Patch: Patched
- Problems: 0

== Exception Information ==
- Thread Information: "Main" (ID: 1552)
- Exception Code: EH_EXCEPTION_NUMBER (0xE06D7363)
- Exception Address: KERNELBASE.dll+0x1498B2 (RaiseException+0x62)
- Exception Flags: 0x1
- Exception Parameters: 0x19930520, 0xCFF0E0, 0x6882066C
C++ Exception: class cpp::bitwizeshift::bad_result_access<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >("error attempting to access value from result containing error")

== Stack Trace ==
- KERNELBASE.dll+0x1498B2 (RaiseException+0x62)
- VCRUNTIME140.dll+0x7E96 (CxxThrowException+0x66)
- maxnu.gd_mega_overlay.dll+0x690A6 (nlohmann::json_abi_v3_11_2::operator<<+0x1456)
- maxnu.gd_mega_overlay.dll+0x6A319 (JsonPatches::init+0x539)
- maxnu.gd_mega_overlay.dll+0xA8633 (init+0x5d3)
- maxnu.gd_mega_overlay.dll+0xA0E7F (std::_Compressed_pair<std::allocator<char>,std::_String_val<std::_Simple_types<char> >,1>::_Compressed_pair<std::allocator<char>,std::_String_val<std::_Simple_types<char> >,1><>+0x4f)
- maxnu.gd_mega_overlay.dll+0x4498B (geode::utils::MiniFunctionState<void (__cdecl*)(void *),void,void *>::call+0xb)
- Geode.dll+0xA743C (geode::ModStateFilter::handle+0x5c)
└ D:\a\geode\geode\loader\src\loader\ModEvent.cpp:21
- maxnu.gd_mega_overlay.dll+0xA0D87 (geode::EventListener<geode::ModStateFilter>::handle+0xb7)
- Geode.dll+0x5ECE3 (geode::DefaultEventListenerPool::handle+0x43)
└ D:\a\geode\geode\loader\src\loader\Event.cpp:33
- Geode.dll+0x5F13C (geode::Event::postFromMod+0x1c)
└ D:\a\geode\geode\loader\src\loader\Event.cpp:91
- Geode.dll+0xACD45 (geode::Mod::Impl::loadBinary+0x205)
└ D:\a\geode\geode\loader\src\loader\ModImpl.cpp:401
- Geode.dll+0x8FF64 (geode::Loader::Impl::loadModGraph::<lambda_0>::operator()+0xb4)
└ D:\a\geode\geode\loader\src\loader\LoaderImpl.cpp:419
- Geode.dll+0x94652 (geode::utils::MiniFunctionState<`lambda at D:\a\geode\geode\loader\src\loader\LoaderImpl.cpp:490:37',void>::call+0x82)
└ D:\a\geode\geode\loader\include\Geode\utils\MiniFunction.hpp:28
- Geode.dll+0x9328F (geode::Loader::Impl::executeMainThreadQueue+0x10f)
└ D:\a\geode\geode\loader\src\loader\LoaderImpl.cpp:807
- Geode.dll+0x4FD52 (geode::modifier::AsStaticFunction_update<FunctionQueue,void (FunctionQueue::*)(float) __attribute__((thiscall))>::Impl<void (FunctionQueue::*)(float) __attribute__((thiscall))>::function+0x12)
└ D:\a\geode\geode\build\bindings\bindings\Geode\modify\CCScheduler.hpp:115
- 0x02F80037
- libcocos2d.dll+0x103223 (cocos2d::CCDirector::levelForSceneInStack+0x83)
- GeometryDash.exe+0x3C12D8 (<0x3c10f0>+0x1e8)
- Geode.dll+0x1765C4 (gdMainHook+0x214)
└ D:\a\geode\geode\loader\src\platform\windows\main.cpp:59
- GeometryDash.exe+0x3C267E (<0x3c1710>+0xf6e)
- KERNEL32.DLL+0x17BA9 (BaseThreadInitThunk+0x19)
- ntdll.dll+0x6BE3B (RtlInitializeExceptionChain+0x6b)
- ntdll.dll+0x6BDBF (RtlClearBits+0xbf)

== Register States ==
- EAX: 00CFEEC0 (-> 0xE06D7363)
- EBX: 19930520 (429065504i | 429065504u)
- ECX: 00000003 (3i | 3u)
- EDX: 00000000 (0i | 0u)
- ESI: 0AD1EF40 (-> 0x30302001)
- EDI: 6882066C (&"")
- EBP: 00CFEF1C (-> 0xCFEF50 -> 0xCFF114 -> 0xCFF16C -> 0xCFF21C -> 0xCFF228 -> 0xCFF234 -> 0xCFF25C -> 0xCFF280 -> 0xCFF2D0 -> 0x6CB1A774 -> 0x6C74F050 -> Geode.dll+0x5F050 (geode::Event::getPool+0x0))
- ESP: 00CFEEC0 (-> 0xE06D7363)
- EIP: 769198B2 (KERNELBASE.dll+0x1498B2 (RaiseException+0x62))
- AF: 1 | CF: 0 | DF: 0 
- IF: 1 | OF: 0 | PF: 1 
- SF: 0 | TF: 0 | ZF: 0 

== Installed Mods ==
~ | [v1.0.0] alphalaneous_raydeeux.changefont19
  | [v1.1.0] artoree.enhanced_menu
~ | [v1.0.4] cdc.level_thumbnails
~ | [v1.0.0] cdc.statuses
~ | [v4.1.10] cvolton.betterinfo
x | [v1.1.3] cvolton.misc_bugfixes
  | [v1.3.7] dankmeme.globed2
~ | [v1.0.4] firee.GoldenBest
~ | [v0.0.3] flafy.autonong
~ | [v2.7.1] fleym.nongd
~ | [v1.5.7] geode.custom-keybinds
x | [v2.0.0-beta.26] geode.loader
x | [v1.9.1] geode.node-ids
~ | [v1.1.0] itzkiba.better_progression
~ | [v1.0.1] mat.draw-divide
o | [v2.10.0] maxnu.gd_mega_overlay
~ | [v1.2.0-beta.4] org.dogotrigger.deathreplay
x | [v1.2.0] prevter.bettercrash
~ | [v1.0.2] relative.account_statuses
~ | [v1.0.3] relative.newgrounds_proxy
~ | [v1.0.0] relative.scroll_faster_with_ctrl
~ | [v1.0.9] syzzi.click_between_frames
  | [v1.1.0] techstudent10.button_sfx
x | [v1.0.0-beta.8] thesillydoggo.comment_emojis
~ | [v1.6.9] thesillydoggo.entersearch
~ | [v1.1.0] tpdea.scroll_any_input
x | [v1.2.2] undefined0.autocheckpoint
~ | [v1.0.2] xiyxs.confirmpracticerestart
x | [v1.0.1] zsa.percentage-bugfix

== Stack Allocations ==
- 0xCFEEC0: E06D7363 (3765269347i | 3765269347u)
- 0xCFEEC4: 00000001 (1i | 1u)
- 0xCFEEC8: 00000000 (0i | 0u)
- 0xCFEECC: 769198B2 (KERNELBASE.dll+0x1498B2 (RaiseException+0x62))
- 0xCFEED0: 00000003 (3i | 3u)
- 0xCFEED4: 19930520 (429065504i | 429065504u)
- 0xCFEED8: 00CFF0E0 (-> 0x687D7CA0 -> 0x6869F060 -> maxnu.gd_mega_overlay.dll+0x3F060 (cpp::bitwizeshift::bad_result_access<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >::~bad_result_access<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >+0x60))
- 0xCFEEDC: 6882066C (&"")
- 0xCFEEE0: 00000009 (9i | 9u)
- 0xCFEEE4: 00D41258 (-> 0xD407D0 -> 0xAD28D90 -> 0xAADD828 -> &"")
- 0xCFEEE8: 00CFEF04 (-> 0xCFEF24 -> 0xE06D7363)
- 0xCFEEEC: 771DC09E (ntdll.dll+0x4C09E (RtlAllocateHeap+0x3e))
- 0xCFEEF0: 00000000 (0i | 0u)
- 0xCFEEF4: 00000000 (0i | 0u)
- 0xCFEEF8: 00000050 (80i | 80u)
- 0xCFEEFC: 00CFF0EC (-> 0xAD69B60 -> &"Cannot enable patch: Failed to enable patch: Unable to write to memory")
- 0xCFEF00: 00CFEF18 (&"O")
- 0xCFEF04: 00CFEF24 (-> 0xE06D7363)
- 0xCFEF08: 76A7F6D8 (ucrtbase.dll+0x2F6D8 (malloc_base+0x28))
- 0xCFEF0C: 01010000 (-> 0x5E902EFF)
- 0xCFEF10: 00000000 (0i | 0u)
- 0xCFEF14: 63B6CA27 (1672923687i | 1672923687u)
- 0xCFEF18: 0000004F (79i | 79u)
- 0xCFEF1C: 00CFEF50 (-> 0xCFF114 -> 0xCFF16C -> 0xCFF21C -> 0xCFF228 -> 0xCFF234 -> 0xCFF25C -> 0xCFF280 -> 0xCFF2D0 -> 0x6CB1A774 -> 0x6C74F050 -> Geode.dll+0x5F050 (geode::Event::getPool+0x0))
- 0xCFEF20: 6CEB7E96 (VCRUNTIME140.dll+0x7E96 (CxxThrowException+0x66))
- 0xCFEF24: E06D7363 (3765269347i | 3765269347u)
- 0xCFEF28: 00000001 (1i | 1u)
- 0xCFEF2C: 00000003 (3i | 3u)
- 0xCFEF30: 00CFEF44 (-> 0x19930520)
- 0xCFEF34: 00000000 (0i | 0u)
- 0xCFEF38: 6C796F01 (Geode.dll+0xA6F01 (geode::Mod::hasAvailableUpdate+0x331))
- 0xCFEF3C: 0AD69B60 (&"Cannot enable patch: Failed to enable patch: Unable to write to memory")`

**Comment by bimbifan** [comment]
same

**Comment by XrussoGD** [comment]
Same I had some botted levels there I had spent a lot of effort on and many other important things and now I had to delete it

**Comment by ghost** [comment]
Misclick whoops, anyway you dont need to delete everything, you can just delete the .geode mod file and replace it with the new one when the fix comes out.

**Comment by XrussoGD** [comment]
Thats what I did, and I hope a fix comes out quickly

**Comment by maxnut** [comment]
fixed
