### ISSUE TITLE
When I click on gui I jump

### ISSUE THREAD

**Issue by ghost** [maxnut/GDmenu#374]
https://github.com/maxnut/GDMegaOverlay/assets/169378045/922c0d76-9b5e-4017-838a-77ac5305ec3f

When I click in the gui I jump! This is a problem mostly in platformers since you want to change something and don't go to the menu, u jump and hit ur head! Also can u make it that when the gui is open it shows the mouse? I'm using a laptop Windows 64-bit. Thanks in advance. (Just wanted to let you know about this if u don't want to fix it)

**Comment by maxnut** [comment]
dont post this here, post it in the discord as a suggestion

**Comment by ghost** [comment]
Will do thanks!
